# Generated by Django 3.2.19 on 2023-05-20 19:46

from django.db import migrations, models

from NEMO.apps.nemo_ce.migration_utils import NEMOMigration


class Migration(NEMOMigration):

    dependencies = [
        ('NEMO', '0045_version_4_5_5'),
        ('nemo_ce', '0007_ce_add_comment_technique_to_trainingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevent',
            name='recorded',
            field=models.BooleanField(default=False, help_text='Indicated this training event has completed and training session was recorded'),
        ),
    ]
